#!/bin/bash
status=$(playerctl --player=spotifyd status)
artUrl=$(playerctl --player=spotifyd metadata --format "{{mpris:artUrl}}")
curl -o "${HOME}/Scripts/songArt.png" $artUrl
song=$(playerctl --player=spotifyd metadata --format "Title: {{ title }}\nArtist: {{ artist }}\nAlbum: {{ album }}")
notify-send -c "spotifyd" "Spotify ($status)" "$song" --icon="${HOME}/Scripts/songArt.png"
